services:

  lambdaban:
    image: ghcr.io/jamestiberiuskirk/lambdaban-web:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lambdaban.rule=Host(`lambdaban.vulpe.dev`)"
      - "traefik.http.routers.lambdaban.entrypoints=web"
      - "traefik.http.services.lambdaban.loadbalancer.server.port=3001"
      - "traefik.http.services.lambdaban.loadbalancer.sticky=true"
      - "traefik.http.services.lambdaban.loadbalancer.sticky.cookie.name=sticky_lambdaban"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PORT: 3001
      METRICS_PORT: 3002
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      migrator:
        condition: service_completed_successfully
    expose:
      - "3001"
      - "3002"

  migrator:
    image: ghcr.io/jamestiberiuskirk/lambdaban-migrator:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db:5432
      DB_DISABLE_SSL: true
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.db-mount:/var/lib/postgresql/data/

  traefik:
    image: traefik:latest
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.lambdaban.vulpe.dev`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
    restart: always

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.lambdaban.vulpe.dev`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    expose:
      - "9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.lambdaban.vulpe.dev`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    expose:
      - "3000"
    depends_on:
      - prometheus
    restart: always

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.lambdaban.vulpe.dev`)"
      - "traefik.http.routers.whoami.entrypoints=web"

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: traefik
