{
 "title": "Lambdaban",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (\n  rate(lambdaban_http_requests_total{code=~\"5..\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code, method, path) (\n  rate(lambdaban_http_requests_total[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "lambdaban_active_users", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SSE Notification Connections",
   "type": "timeseries",
   "description": "Amount of users connected to servers send events notification endpoint ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "lambdaban_sse_active_notification_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}